### ISSUE TITLE
fake "base"-groups

### ISSUE THREAD

**Issue by lazka** [msys2/msys2-web#47]
similar to pkgbase we could fake a base group name in the UI. Every group showing up multiple times is starting to get confusing.

**Comment by Biswa96** [comment]
> Every group showing up multiple times is starting to get confusing.

Example?

**Comment by lazka** [comment]
* mingw-w64-toolchain
  * mingw-w64-ucrt-x86_64-toolchain
  * mingw-w64-x86_64-toolchain
  * mingw-w64-clang-i686-toolchain
  * mingw-w64-clang-x86_64-toolchain
  * mingw-w64-i686-toolchain
