### ISSUE TITLE
Make everything makedepend on base/base-devel

### ISSUE THREAD

**Issue by lazka** [msys2/msys2-web#52]
When figuring out the build order and dependencies. So that autobuild builds everything in base/base-devel first and also pulls it in if needed.

**Comment by lazka** [comment]
This will result in lots of cycles though, so not sure.

**Comment by Biswa96** [comment]
Can you provide pros and cons and what issue will be solved by this change? Just curious.

**Comment by lazka** [comment]
All packages implicitly depend on everything in "base" and "base-devel" to build.

PRO: So let's say if `sed` is in the queue and `mingw-w64-gtk3` then `sed` should be built first, because gtk3 *might* use it.

CON: On the other hand if `grep` and `sed` are in the queue, so two packages in base, then both would be in a cycle because they depend on `base` and thus on each other. While in theory correct this might mean more manual work.

**Comment by lazka** [comment]
Done in 073e2db502b1def2
