### ISSUE TITLE
package site is down

### ISSUE THREAD

**Issue by ReenigneArcher** [msys2/msys2-web#70]
Just opening an issue in case no one is aware yet

https://packages.msys2.org/ is down. Might be a certificate issue?

![image](https://github.com/msys2/msys2-web/assets/42013603/ed1e5bee-32c8-414f-8a79-b7f33035d92e)

Also, can't download packages such as `https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-curl-8.8.0-1-any.pkg.tar.zst`

**Comment by Biswa96** [comment]
If you want to download old packages try to use any mirror from `/etc/pacman.d/mirrorlist*` file.

**Comment by ReenigneArcher** [comment]
Thanks! Everything seems to be back up now.
